version: "3.8"

services:
    app:
        build:
            context: .
        container_name: laravel_backend
        volumes:
            - .:/var/www
        networks:
            - laravel
        depends_on:
            - db
        restart: unless-stopped

    nginx:
        image: nginx:alpine
        container_name: nginx_laravel
        depends_on:
            - app
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
        ports:
            - "80:80"
            - "443:443"
        networks:
            - laravel
        restart: unless-stopped

    # certbot:
    #     image: certbot/certbot
    #     container_name: certbot_laravel
    #     volumes:
    #         - certbot-etc:/etc/letsencrypt
    #         - certbot-var:/var/lib/letsencrypt
    #         - .:/var/www
    #     entrypoint: /bin/sh -c
    #     command: >
    #         "sleep 15 &&
    #         certbot certonly --webroot -w /var/www/public
    #         --email inkkyt60@gmail.com --agree-tos --no-eff-email
    #         -d api.domainmu.com"
    #     networks:
    #         - laravel

    db:
        image: postgres:15
        container_name: postgres_laravel
        restart: unless-stopped
        environment:
            POSTGRES_DB: hris-database
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: sonyfebri04
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel

    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        restart: always
        ports:
            - "9001:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        networks:
            - laravel # digabung ke network yang sama

volumes:
    certbot-etc:
    certbot-var:
    pgdata:
    portainer_data:

networks:
    laravel:
